### ISSUE TITLE
Implement loading of trusted setup

### ISSUE THREAD

**Issue by joebebel** [anomanetwork/ferveo#17]
If KZG commitments are used, then a trusted setup has to be loaded (probably an existing setup, Zcash or Filecoin)

This is a straightforward task, implement in Rust the download/verification/loading of the trusted setup. Ideally there should be extensive opportunity for code reuse/external crates here, since for example Zcash clients perform this task exactly.

**Comment by ggkitsas** [comment]
https://github.com/zcash/librustzcash/blob/master/zcash_proofs/src/lib.rs

**Comment by joebebel** [comment]
This code can probably be modified to do a powers of tau setup for BLS12-377 if needed:

https://github.com/arielgabizon/perpetualpowersoftau

**Comment by ggkitsas** [comment]
Update:

temporarily hosting our effort here https://github.com/heliaxdev/trusted-setup/

So far: 
* can deserialize and load the powers-of-tau as hosted by zcash (https://download.z.cash/downloads/powersoftau/)
  * not able to map params appropriatelly to make KZG work
* used https://github.com/ebfull/powersoftau/ to generate parameters with known tau to help in further examination/debugging
  * currently trying to find a way to deserialize them

**Comment by ggkitsas** [comment]
* Downloading the KZG parameters is implemented here: https://github.com/heliaxdev/trusted-setup/blob/master/src/lib.rs#L119
* The KZG parameters file is a preprocessed (for efficiency reasons) file from the powersoftau ([this](https://powersoftau-transcript.s3-us-west-2.amazonaws.com/88dc1dc6914e44568e8511eace177e6ecd9da9a9bd8f67e4c0c9f215b517db4d1d54a755d051978dbb85ef947918193c93cd4cf4c99c0dc5a767d4eeb10047a4) is the download link). The process is described [here](https://github.com/heliaxdev/trusted-setup/blob/master/src/bin/preprocess.rs) for verification and replicability
* Loading the parameters is implemented here: https://github.com/heliaxdev/trusted-setup/blob/master/src/lib.rs#L156
