### ISSUE TITLE
Batch pairings for threshold operations

### ISSUE THREAD

**Issue by joebebel** [anomanetwork/ferveo#33]
Decrypting involves a number of pairing checks, as @simonmasson observes we can optimize that to two miller loops and one final exp ([example](https://github.com/heliaxdev/ferveo/tree/simon/bls-pairing-equation).

Additionally since many transactions are getting decrypted at the same time, it would be nice to batch all these checks together (e.g. because you're verifying a bunch of decryptions made with the same key share).

Since tx decryption is going to need to be very fast it's worth looking at these optimizations

**Comment by ggkitsas** [comment]
miller-loop optimization is already implemented in `product_of_pairings` in arkworks (https://github.com/arkworks-rs/algebra/blob/9847e36d4481526fdcfc05c4152d96d9abd50453/ec/src/lib.rs#L100).

Will group the checks for multi-tx decryption

**Comment by ggkitsas** [comment]
Grouping checks for multi-tx has two optimizations:
1. the afformentioned final exp optimization
2. due to bilinearity the pairings on the G1 generator and authentication tags can be compressed to one pairing operation:
    `\prod{e(P, W_i)} = e(P, \sum{W_i})`
